[36m--[0m Using CATKIN_DEVEL_PREFIX: /app/devel/.private/gather_data
[36m--[0m Using CMAKE_PREFIX_PATH: /app/devel;/opt/ros/noetic
[36m--[0m This workspace overlays: /app/devel;/opt/ros/noetic
[36m--[0m Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3")
[36m--[0m Using PYTHON_EXECUTABLE: /usr/bin/python3
[36m--[0m Using Debian Python package layout
[36m--[0m Using empy: /usr/lib/python3/dist-packages/em.py
[36m--[0m Using CATKIN_ENABLE_TESTING: ON
[36m--[0m Call enable_testing()
[36m--[0m Using CATKIN_TEST_RESULTS_DIR: /app/build/gather_data/test_results
[36m--[0m Forcing gtest/gmock from source, though one was otherwise available.
[36m--[0m Found gtest sources under '/usr/src/googletest': gtests will be built
[36m--[0m Found gmock sources under '/usr/src/googletest': gmock will be built
[36m--[0m Found PythonInterp: /usr/bin/python3 (found version "3.8.10")
[36m--[0m Using Python nosetests: /usr/bin/nosetests3
[36m--[0m catkin 0.8.10
[36m--[0m BUILD_SHARED_LIBS is on
[31m[1mCMake Error[0m at /opt/ros/noetic/share/catkin/cmake/catkin_python_setup.cmake:81 (message):
  The package name 'gather_data/utilx' differs from the basename of the path
  'src/gather_data/utilx' in project 'gather_data'
[36mCall Stack (most recent call first):[0m
  CMakeLists.txt:22 (catkin_python_setup)


[36m--[0m Configuring incomplete, errors occurred!
See also "/app/build/gather_data/CMakeFiles/CMakeOutput.log".
See also "/app/build/gather_data/CMakeFiles/CMakeError.log".
make: *** [Makefile:390: cmake_check_build_system] Error 1
